development:
  adapter:  postgresql
  host:     localhost
  username: rails
  password: 123456
  database: hellorails_development
  encoding: utf8
  timeout:  5000

test:
  adapter:  postgresql
  host:     localhost
  username: rails
  password: 123456
  database: hellorails_test
  encoding: utf8
  timeout:  5000

production:
  adapter:  postgresql
  host:     localhost
  username: rails
  password: 123456
  database: hellorails_production
  encoding: utf8
  timeout:  5000